---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (centos)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
  - name: install updates (ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
 
- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages for ubuntu servers
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: install apache2 and php packages for centos servers
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_server
  become: true
  tasks:
 
  - name: install mariabd package (centos)
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_server
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
