- name: install mariabd package (centos)
  tags: centos,db,mariadb
  yum:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb package (ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
